### PR TITLE
Node tool

### PR DESCRIPTION
**Pull request by SomeHats**
This PR replaces the original cs tool with a (hopefully) cross-platform one written in Node. As well as the command line interface, the tool can be used programmatically in any node project that `require`s this package, which should make it easy for people to plug this into the various node build tools. I've updated the README, which assumes you will publish this to npm.

Currently missing from this tool compared to the original:
- No `-r` recursive option, as this can be achieved with globbing: `$ wb encode folder/**/*`
- No `-h` encryption option, as I'm not sure what it's useful for

I can add these if needed.

I don't have a windows machine to test this on, but everything in `tool/` should be platform-independent. There are a couple of quick-and-dirty tests in `test/` (run them with `$ npm test`) but they use `/` in file paths, which might make node on windows upset.

### CODE REVIEW

**Comment by eduardo-costa** [comment]
Wow! Huge thanks!
I guess that if it works outside windows w/ node, it will work just fine.
I don't have the experience to publish in `npm` so if you can handle this part it would be great!

Regarding the `-r` option, if globbing works then it is fine as you can have it and much more filtering options.

The `-h`option is interesting if users would like a simple security measure of encryption his data.
The algorithm is pretty straightforward.

```
//.wb data layout
//0         len-1 
//[header string][0][file0-bytes][file1-bytes]...[fileN-1-bytes]

//If -h is used
var password = h_argument;

var file_bytes_buffer = concatenated_file_bytes;
var pass_char_it = 0;
//iterate all bytes and apply a bit XOR
//this operations scramble the bits but is reversible if applied again
// ((byte ^ mask) ^ mask) == byte
for(var i=0;i<file_bytes_buffer.length;i++)
{
    var v = file_bytes_buffer[i];
    v =  v ^ password.charCodeAt(pass_char_it++); //simple bit XOR masking encryption
    pass_char_it = pass_char_it % password.length
    file_bytes_buffer[i] = v;
}

//if password is 'abcde' the XOR op will applied like this
[b0,b1,b2,b3,b4,b5,b6,b7,...]
 ^  ^  ^  ^  ^  ^  ^  ^
[a ,b ,c ,d ,e ,a ,b ,c ,...]

PNGWrite([header,0,file_bytes_buffer]); //write a masked file byte array
```

If users try to decode the PNG and don't use the same password the inverse bit XOR will fail to convert the encrypted to the original data.
So you only need to apply `byte ^ mask` when writing or reading the data sector of the WebBundle!

**Comment by eduardo-costa** [comment]
You added nice extra features in the CLI!

Finishing the `-h` feature I can merge everything and try to even create a web service in my amazon server to test it!

The `npm`package can come later then!
If you have questions just PM me!

**Comment by SomeHats** [comment]
Done! If you can create a version tag and bump the version in `package.json`, I'll publish to npm :)

**Comment by eduardo-costa** [comment]
Where I need to create this file?

**Comment by SomeHats** [comment]
1. First, edit `package.json` (and I guess `haxelib.json`) to increase the version number - probably 1.1
2. Create a tag - either with `$ git tag v1.1.0; git push --tags` or with github's release thing, which might be easier: https://github.com/haxorplatform/web-bundle/releases/new
3. Let me no, and I'll publish to npm, or you can do it your self with `$ npm publish`

**Comment by eduardo-costa** [comment]
We are up!
I added your user in the contributors (I guess)..
You are welcome to fix anything if there is problem!

https://www.npmjs.com/package/web-bundle

Thanks!

**Pull request merged**
